# Generated by Django 5.2.4 on 2025-08-11 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='marketing_banner',
            field=models.ImageField(blank=True, null=True, upload_to='marketing_banners/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='widget_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('extended', 'Extended'), ('pro', 'Pro')], default='basic', max_length=10),
        ),
        migrations.CreateModel(
            name='MonthlyRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('average_rating', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
