# Generated by Django 5.2.4 on 2025-08-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_marketing_banner_customuser_widget_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='monthly_reply_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='plan_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
