# Generated by Django 5.2.4 on 2025-10-24 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_email_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('medical', 'Medical Services / Dentistry'), ('beauty', 'Beauty Industry / Salon / Barbershop'), ('retail', 'Retail Store (Offline)'), ('ecommerce', 'Online Store (E-commerce)'), ('hotel', 'Hotel / Apartments / Guesthouse'), ('auto_service', 'Auto Service / Car Wash / Tire Shop'), ('car_dealership', 'Car Dealership / Auto Sales'), ('education', 'Education / Courses / Online School'), ('tourism', 'Tourism / Travel Agency / Excursions'), ('renovation', 'Renovation / Construction / Finishing'), ('it_services', 'IT Services / Development / Support'), ('logistics', 'Logistics / Delivery / Courier Service'), ('real_estate', 'Real Estate / Agency / Rental'), ('household', 'Household Services / Cleaning / Appliance Repair'), ('veterinary', 'Veterinary / Grooming / Pet Care'), ('financial', 'Financial / Insurance / Legal Services'), ('wellness', 'Health & Wellness (Fitness, Massage, Spa)'), ('photography', 'Photography / Video Production'), ('furniture', 'Furniture / Interior Design'), ('telecom', 'Telecommunications / Internet Providers')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='🏢', max_length=10)),
                ('questions', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic Level'), ('advanced', 'Advanced Level'), ('pro', 'Pro Level'), ('unique', 'Unique Level'), ('expired', 'Expired')], default='basic', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.businesscategory'),
        ),
    ]
