# Generated by Django 5.2.4 on 2026-02-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_businesscategory_alter_customuser_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='max_branches',
            field=models.PositiveIntegerField(blank=True, help_text='Max branches for unique plan', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_offline_review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='offline_limit_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Offline review limit for unique plan', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='online_limit_per_month',
            field=models.PositiveIntegerField(blank=True, help_text='Online review limit for unique plan', null=True),
        ),
    ]
