# Generated by Django 5.2.4 on 2026-03-26 22:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='marketing_banner',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='marketing_banner'),
        ),
    ]
