# Generated by Django 5.2.4 on 2026-04-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_marketing_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='marketing_banner',
            field=models.ImageField(blank=True, null=True, upload_to='marketing_banners/'),
        ),
    ]
