# Generated by Django 5.2.4 on 2025-07-31 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_review_token_order_user_alter_order_order_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('main_rating', models.PositiveSmallIntegerField(default=5)),
                ('logistics_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('communication_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('website_usability_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_flagged_red', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_publish_at', models.DateTimeField(blank=True, null=True)),
                ('reply', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
