# Generated by Django 5.2.4 on 2025-08-02 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('recommend', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('main_rating', models.PositiveSmallIntegerField(default=5)),
                ('logistics_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('communication_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('website_usability_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_flagged_red', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('auto_publish_at', models.DateTimeField(blank=True, null=True)),
                ('reply', models.TextField(blank=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order')),
            ],
        ),
    ]
