# Generated by Django 5.2.4 on 2025-10-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='category_ratings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
