# Generated by Django 5.2.4 on 2025-10-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_category_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='manual_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='manual_customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='manual_customer_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]


