# Generated by Django 5.2.4 on 2026-01-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_mailingtemplate_mailingcampaign_mailingrecipient_and_more'),
        ('reviews', '0004_manual_review_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order'),
        ),
    ]
