# Generated by Django 5.2.4 on 2026-02-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_review_source_branch_review_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='manual_customer_address',
            field=models.TextField(blank=True, help_text='Customer address (optional)', null=True),
        ),
    ]
