# Generated by Django 5.2.4 on 2025-08-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='review_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
