# Generated by Django 5.2.4 on 2026-02-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_mailingtemplate_mailingcampaign_mailingrecipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingrecipient',
            name='country',
            field=models.CharField(blank=True, help_text="Recipient's country for language localization (e.g., 'Czech', 'Slovak', 'en')", max_length=100),
        ),
    ]
